// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmulxkqsyvzryrxoutpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdWx4a3FzeXZ6cnlyeG91dHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjYyODUsImV4cCI6MjA2NDM0MjI4NX0.r4hE_uGC35Opvv0iQxAssXK_cevdQfZUXfLt0Gdelmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});